/**
 * GitHub Pages project URL: /<repo>/  → marketing at /tech-updates/index.html,
 * osmosfeed reader at /tech-updates/feed/ (relative "feed/" links on landing work).
 *
 * Flow: backup landing + cache seed + SEO → empty public/ → osmosfeed build
 * → move all generator output into public/feed/ → restore landing + SEO.
 * On any failure, public/ is cleared of partial output and landing/SEO restored.
 */
import { spawnSync } from "node:child_process";
import fs from "fs-extra";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const publicDir = path.join(root, "public");
const feedDir = path.join(publicDir, "feed");
const publicLanding = path.join(publicDir, "index.html");
const landingSrc = path.join(root, "landing", "index.html");
const landingStash = path.join(root, ".build-landing-index.html");
const cacheStash = path.join(root, ".build-osmosfeed-cache.json");
const seoStashDir = path.join(root, ".build-public-seo-stash");
const stylesStashDir = path.join(root, ".build-public-styles-stash");
const scriptsStashDir = path.join(root, ".build-public-scripts-stash");

function runOsmosfeed() {
  const result = spawnSync("npx", ["osmosfeed", "build"], {
    cwd: root,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    const code = result.status ?? 1;
    throw new Error(`osmosfeed build failed (exit ${code})`);
  }
}

async function main() {
  await fs.ensureDir(publicDir);

  // Interrupted previous run: no homepage on disk but stash exists
  if (
    !(await fs.pathExists(publicLanding)) &&
    (await fs.pathExists(landingStash))
  ) {
    await fs.copy(landingStash, publicLanding);
    console.warn("[build] Restored public/index.html from .build-landing-index.html");
  }

  // Canonical landing bytes for this run (public wins over landing/)
  if (await fs.pathExists(publicLanding)) {
    await fs.copy(publicLanding, landingStash, { overwrite: true });
  } else if (await fs.pathExists(landingSrc)) {
    await fs.copy(landingSrc, landingStash, { overwrite: true });
  } else {
    console.error(
      "[build] Missing homepage source: need public/index.html or landing/index.html",
    );
    process.exit(1);
  }

  // Incremental cache: keep last feed cache outside public before we wipe it
  const prevCache = path.join(feedDir, "cache.json");
  if (await fs.pathExists(prevCache)) {
    await fs.copy(prevCache, cacheStash, { overwrite: true });
  } else {
    await fs.remove(cacheStash).catch(() => {});
  }

  // Keep robots/sitemap across clean (not generated by osmosfeed)
  await fs.remove(seoStashDir).catch(() => {});
  await fs.ensureDir(seoStashDir);
  for (const name of ["robots.txt", "sitemap.xml"]) {
    const p = path.join(publicDir, name);
    if (await fs.pathExists(p)) {
      await fs.copy(p, path.join(seoStashDir, name), { overwrite: true });
    }
  }

  await fs.remove(stylesStashDir).catch(() => {});
  const publicStyles = path.join(publicDir, "styles");
  if (await fs.pathExists(publicStyles)) {
    await fs.copy(publicStyles, stylesStashDir, { overwrite: true });
  }

  await fs.remove(scriptsStashDir).catch(() => {});
  const publicScripts = path.join(publicDir, "scripts");
  if (await fs.pathExists(publicScripts)) {
    await fs.copy(publicScripts, scriptsStashDir, { overwrite: true });
  }

  let buildFailed = false;

  try {
    await fs.emptyDir(publicDir);

    if (await fs.pathExists(cacheStash)) {
      await fs.copy(cacheStash, path.join(publicDir, "cache.json"));
    }

    runOsmosfeed();

    await fs.ensureDir(feedDir);
    const top = await fs.readdir(publicDir);
    for (const name of top) {
      if (name === "feed") continue;
      const from = path.join(publicDir, name);
      const to = path.join(feedDir, name);
      await fs.move(from, to, { overwrite: true });
    }
  } catch (err) {
    buildFailed = true;
    console.error("[build]", err.message || err);
    await fs.emptyDir(publicDir).catch(() => {});
  } finally {
    await fs.ensureDir(publicDir);
    if (await fs.pathExists(landingStash)) {
      await fs.copy(landingStash, publicLanding, { overwrite: true });
    }
    if (await fs.pathExists(seoStashDir)) {
      const files = await fs.readdir(seoStashDir).catch(() => []);
      for (const name of files) {
        await fs.copy(
          path.join(seoStashDir, name),
          path.join(publicDir, name),
          { overwrite: true },
        );
      }
    }
    if (await fs.pathExists(stylesStashDir)) {
      await fs.copy(stylesStashDir, path.join(publicDir, "styles"), {
        overwrite: true,
      });
    }
    if (await fs.pathExists(scriptsStashDir)) {
      await fs.copy(scriptsStashDir, path.join(publicDir, "scripts"), {
        overwrite: true,
      });
    }
    await fs.ensureDir(feedDir);
  }

  if (buildFailed) {
    process.exit(1);
  }

  const feedIndex = path.join(feedDir, "index.html");
  if (!(await fs.pathExists(feedIndex))) {
    console.error("[build] Missing public/feed/index.html after build");
    process.exit(1);
  }

  console.log(
    "[build] OK — landing: public/index.html · reader: public/feed/index.html",
  );
}

main().catch((e) => {
  console.error("[build]", e);
  process.exit(1);
});
